### ISSUE TITLE
Demo on JSFiddle is broken on Chrome with strict mime type checking enabled...

### ISSUE THREAD

**Issue by jblashill** [LinkedInAttic/Backbone.TableView#16]
FYI, using Chrome 27 I wasn't able to run your demo without pointing the backbone.tableview.js file to somewhere that responded with the correct mime type (unlike github). Here's the error i got:

Refused to execute script from 'https://raw.github.com/linkedin/Backbone.TableView/master/backbone.tableview.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by jpbottaro** [comment]
Hey James,

Thanks for the report! I've hosted it in the github.io domain now and that fixed it.

Thanks,
JP
