### ISSUE TITLE
Remove dependence on Backbone.History

### ISSUE THREAD

**Issue by ghost** [LinkedInAttic/Backbone.TableView#5]
Unless I'm mistaken, it seems that TableView in its current form is dependent upon the use of Backbone.History.  Is this necessary?

For example, on line 113 in JS, in TableView.prototype.initialize():

``` js
TableView.prototype.initialize = function() {
//...
this.data = $.extend({}, this.initialData, this.parseQueryString(Backbone.history.fragment));
```

this code block is called without checking to see if Backbone.history exists.

Yet elsewhere in the code, in TableView.prototype.updateUrl() (line 193 in JS):

``` js
TableView.prototype.updateUrl = function(replace) {
//...
if (this.router) {
    uri = Backbone.history.fragment;
}
```

You check for the existence of this.router before attempting to access Backbone.history.fragment.

Is the use of Backbone.History necessary for TableView, and if not, can this issue be corrected?

I "fixed" this by performing another check in TableView.prototype.initialize for this.router before merging data from this.parseQueryString(Backbone.history.fragment) into this.data.  ex:

``` js
this.data = $.extend({}, this.initialData);
if (this.router) {
    this.data = $.extend(this.data, this.parseQueryString(Backbone.history.fragment));
}
```
- SHA: ce3bd561e06b966aac0cfd4da336e8ea0de182b7
- backbone.tableview.js: https://github.com/linkedin/Backbone.TableView/blob/ce3bd561e06b966aac0cfd4da336e8ea0de182b7/backbone.tableview.js

**Comment by jpbottaro** [comment]
Thanks for this fragnemesis! I did the fix you described in coffeescript.
